version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.46
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --ver