version: 2.1

jobs:
  build:
    docker:
      - image: rust:1.46
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Add wasm32 target
          command: rustup target add w